# Generated by Django 6.1.1 on 2026-09-24 08:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='شماره رسید')),
                ('transaction_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع تراکنش')),
                ('category', models.CharField(choices=[('visit_fee', 'ویزیت'), ('service', 'خدمات'), ('product_sale', 'فروش اقلام'), ('other_income', 'سایر درآمدها'), ('purchase', 'خرید'), ('rent', 'اجاره'), ('salary', 'حقوق'), ('equipment', 'تجهیزات'), ('current_expense', 'هزینه جاری'), ('other_expense', 'سایر هزینه\u200cها')], max_length=30, verbose_name='دسته\u200cبندی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (تومان)')),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='patients.patient', verbose_name='بیمار')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='records.visit', verbose_name='مراجعه مرتبط')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['-transaction_date'], name='tx_date_idx'), models.Index(fields=['transaction_type', '-transaction_date'], name='tx_type_date_idx'), models.Index(fields=['category'], name='tx_category_idx'), models.Index(fields=['patient'], name='tx_patient_idx')],
            },
        ),
    ]
