# Generated by Django 6.1.1 on 2026-09-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('patients', '0002_alter_patient_options_patient_assigned_consultant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='patients.patient', verbose_name='مراجع'),
        ),
    ]
