# Generated by Django 6.1.1 on 2026-09-24 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان سطح')),
                ('code', models.SlugField(unique=True, verbose_name='کد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('standard_minutes', models.PositiveIntegerField(default=45, verbose_name='زمان استاندارد (دقیقه)')),
                ('base_price', models.DecimalField(decimal_places=0, help_text='مبلغ جلسهٔ استاندارد', max_digits=12, verbose_name='مبلغ پایه (تومان)')),
                ('overtime_per_minute', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینهٔ هر دقیقهٔ مازاد (تومان)')),
                ('grace_minutes', models.PositiveIntegerField(default=5, help_text='دقایق اول بعد از استاندارد که رایگان است', verbose_name='دقایق ارفاق')),
                ('rounding_minutes', models.PositiveIntegerField(default=5, help_text='۰ = بدون رُند، ۵ = هر ۵ دقیقه یک پله', verbose_name='رُند کردن (دقیقه)')),
                ('max_minutes', models.PositiveIntegerField(default=120, verbose_name='حداکثر زمان مجاز (دقیقه)')),
                ('insurance_share', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سهم بیمه (تومان)')),
                ('effective_from', models.DateField(verbose_name='از تاریخ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('color', models.CharField(default='#2563eb', max_length=7, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سطح مشاور',
                'verbose_name_plural': 'سطوح مشاور',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='رزومه'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.JSONField(blank=True, default=list, verbose_name='تخصص\u200cها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consultant', 'مشاور'), ('secretary', 'منشی'), ('manager', 'مدیر مرکز')], default='secretary', max_length=20, verbose_name='نقش'),
        ),
        migrations.AddField(
            model_name='user',
            name='consultant_level',
            field=models.ForeignKey(blank=True, help_text='فقط برای نقش مشاور پر می\u200cشود', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultants', to='accounts.consultantlevel', verbose_name='سطح مشاور'),
        ),
        migrations.CreateModel(
            name='ConsultantSlotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_minutes', models.PositiveIntegerField(default=50, verbose_name='طول هر اسلات (دقیقه)')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, verbose_name='فاصلهٔ بین اسلات\u200cها (دقیقه)')),
                ('max_daily_sessions', models.PositiveIntegerField(default=8, verbose_name='حداکثر جلسات روزانه')),
                ('allow_overlap', models.BooleanField(default=False, help_text='اجازهٔ رزرو هم\u200cپوشان (مثلاً گروه\u200cدرمانی)', verbose_name='اجازهٔ هم\u200cپوشانی')),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_settings', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'تنظیمات اسلات',
                'verbose_name_plural': 'تنظیمات اسلات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ConsultantScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(db_index=True, verbose_name='از تاریخ')),
                ('to_date', models.DateField(db_index=True, verbose_name='تا تاریخ')),
                ('is_off', models.BooleanField(default=False, help_text='اگر بله، این بازه کاملاً تعطیل است', verbose_name='تعطیل کامل')),
                ('custom_start', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع ویژه')),
                ('custom_end', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان ویژه')),
                ('apply_to_all_weekdays', models.BooleanField(default=True, verbose_name='اعمال روی همهٔ روزهای هفته')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'استثنای برنامه',
                'verbose_name_plural': 'استثناهای برنامه',
                'ordering': ['-from_date'],
                'indexes': [models.Index(fields=['consultant', 'from_date', 'to_date'], name='accounts_co_consult_1614ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultantWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'برنامهٔ هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('consultant', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ تغییر')),
                ('change_type', models.CharField(choices=[('activate', 'فعال\u200cسازی'), ('deactivate', 'غیرفعال\u200cسازی'), ('time_change', 'تغییر ساعت'), ('leave', 'مرخصی'), ('room_change', 'تغییر اتاق'), ('bulk_update', 'به\u200cروزرسانی گروهی')], max_length=20, verbose_name='نوع تغییر')),
                ('before', models.JSONField(default=dict, verbose_name='قبل')),
                ('after', models.JSONField(default=dict, verbose_name='بعد')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_history', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'تغییر برنامه',
                'verbose_name_plural': 'تغییرات برنامه',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultant', '-created_at'], name='accounts_sc_consult_0196cc_idx'), models.Index(fields=['date'], name='accounts_sc_date_204876_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecretaryShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('section', models.CharField(choices=[('reception', 'پذیرش و ارسال به مشاور'), ('followup', 'پیگیری رزرو و کنسلی'), ('finance', 'صندوق و پرداخت'), ('full', 'دسترسی کامل')], default='full', max_length=20, verbose_name='بخش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='منشی')),
            ],
            options={
                'verbose_name': 'شیفت منشی',
                'verbose_name_plural': 'شیفت\u200cهای منشی',
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'section'], name='accounts_se_date_9d6b69_idx'), models.Index(fields=['secretary', '-date'], name='accounts_se_secreta_0e18e8_idx')],
            },
        ),
    ]
