# Generated by Django 6.1.1 on 2026-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consultantlevel_user_bio_user_specialties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantweeklyschedule',
            name='blocked_hours',
            field=models.JSONField(blank=True, default=list, help_text='لیست ساعت\u200cهای غیرفعال — مثلاً [12, 13]', verbose_name='ساعت\u200cهای غیرفعال'),
        ),
    ]
