# Generated by Django 6.1.1 on 2026-09-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='کلید لایسنس')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره سریال')),
                ('tier', models.CharField(choices=[('trial', 'آزمایشی'), ('basic', 'پایه'), ('pro', 'حرفه\u200cای'), ('enterprise', 'سازمانی')], default='trial', max_length=20, verbose_name='نوع لایسنس')),
                ('licensed_to', models.CharField(blank=True, max_length=200, verbose_name='صادر شده برای')),
                ('licensed_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('licensed_phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('max_users', models.PositiveIntegerField(default=3, verbose_name='حداکثر کاربران')),
                ('max_physicians', models.PositiveIntegerField(default=1, verbose_name='حداکثر پزشکان')),
                ('max_branches', models.PositiveIntegerField(default=1, verbose_name='حداکثر شعب')),
                ('enable_inventory', models.BooleanField(default=True, verbose_name='انبار')),
                ('enable_finance', models.BooleanField(default=True, verbose_name='مالی')),
                ('enable_therapies', models.BooleanField(default=True, verbose_name='درمان\u200cهای تخصصی')),
                ('enable_documents', models.BooleanField(default=True, verbose_name='مدارک')),
                ('enable_consent', models.BooleanField(default=True, verbose_name='رضایت\u200cنامه')),
                ('enable_reports', models.BooleanField(default=True, verbose_name='گزارش\u200cها')),
                ('enable_backup', models.BooleanField(default=True, verbose_name='پشتیبان\u200cگیری')),
                ('enable_audit', models.BooleanField(default=True, verbose_name='گزارش فعالیت\u200cها')),
                ('enable_appointments', models.BooleanField(default=True, verbose_name='نوبت\u200cدهی')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فعال\u200cسازی')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی'), ('suspended', 'معلق'), ('not_activated', 'فعال\u200cنشده')], default='not_activated', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه نرم\u200cافزار')),
                ('installation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='شناسه نصب')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لایسنس',
                'verbose_name_plural': 'لایسنس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_run_date', models.DateField(verbose_name='تاریخ اولین اجرا')),
                ('machine_fingerprint', models.CharField(max_length=64, verbose_name='شناسه سخت\u200cافزار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'وضعیت Trial',
                'verbose_name_plural': 'وضعیت Trial',
            },
        ),
    ]
