# Generated by Django 6.1.1 on 2026-09-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='مطب طبیب', max_length=200, verbose_name='نام مطب')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='نام پزشک')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='تخصص')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='شماره پروانه')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='همراه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/', verbose_name='لوگو')),
                ('footer_note', models.TextField(blank=True, default='این نسخه صرفاً جهت اطلاع و مصرف بیمار صادر شده است.', verbose_name='یادداشت پایین نسخه')),
                ('prescription_header', models.TextField(blank=True, help_text='متن ثابتی که در ابتدای نسخه چاپ می\u200cشود.', verbose_name='سربرگ نسخه')),
                ('require_payment_for_appointment', models.BooleanField(default=False, help_text='اگه فعال باشه، بیماران قبل از نوبت باید مبلغ ویزیت رو پرداخت کنن.', verbose_name='الزام پرداخت برای نوبت\u200cها')),
                ('default_appointment_fee', models.DecimalField(blank=True, decimal_places=0, help_text='برای محاسبه\u200cی خودکار مبلغ نوبت\u200cها', max_digits=14, null=True, verbose_name='مبلغ پیش\u200cفرض ویزیت (تومان)')),
                ('appointment_slot_duration', models.PositiveSmallIntegerField(default=15, help_text='پیش\u200cفرض: ۱۵ دقیقه برای ویزیت معمولی', verbose_name='طول پیش\u200cفرض هر نوبت (دقیقه)')),
            ],
            options={
                'verbose_name': 'تنظیمات مطب',
                'verbose_name_plural': 'تنظیمات مطب',
            },
        ),
    ]
