# Generated by Django 6.1.1 on 2026-09-24 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام اتاق')),
                ('code', models.SlugField(unique=True, verbose_name='کد')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='ظرفیت')),
                ('color', models.CharField(default='#06b6d4', max_length=7, verbose_name='رنگ در تایم\u200cلاین')),
                ('equipment', models.TextField(blank=True, help_text='مثلاً: پروژکتور، مبل راحتی، میز بازی\u200cدرمانی', verbose_name='تجهیزات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clinicsettings',
            options={'verbose_name': 'تنظیمات مرکز', 'verbose_name_plural': 'تنظیمات مرکز'},
        ),
        migrations.RemoveField(
            model_name='clinicsettings',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='clinicsettings',
            name='prescription_header',
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='booking_horizon_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='چند ماه جلوتر می\u200cتوان نوبت گرفت', verbose_name='بازهٔ مجاز رزرو (ماه)'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='invoice_header',
            field=models.TextField(blank=True, help_text='متن ثابتی که در ابتدای فاکتور چاپ می\u200cشود.', verbose_name='سربرگ فاکتور'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام مدیر'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='appointment_slot_duration',
            field=models.PositiveSmallIntegerField(default=50, help_text='پیش\u200cفرض: ۵۰ دقیقه برای جلسهٔ مشاوره', verbose_name='طول پیش\u200cفرض هر جلسه (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='مرکز مشاوره', max_length=200, verbose_name='نام مرکز'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='default_appointment_fee',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='برای محاسبه\u200cی خودکار مبلغ نوبت\u200cها', max_digits=14, null=True, verbose_name='مبلغ پیش\u200cفرض مشاوره (تومان)'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='footer_note',
            field=models.TextField(blank=True, default='از اعتماد شما سپاسگزاریم.', verbose_name='یادداشت پایین فاکتور'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='require_payment_for_appointment',
            field=models.BooleanField(default=False, help_text='اگه فعال باشه، مراجعین قبل از نوبت باید مبلغ مشاوره رو پرداخت کنن.', verbose_name='الزام پرداخت برای نوبت\u200cها'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='تخصص / رویکرد'),
        ),
        migrations.CreateModel(
            name='ConsultantRoomChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('changed_at', models.DateTimeField(verbose_name='زمان تغییر')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_changes', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('from_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinic.room', verbose_name='از اتاق')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinic.room', verbose_name='به اتاق')),
            ],
            options={
                'verbose_name': 'تغییر اتاق',
                'verbose_name_plural': 'تغییرات اتاق',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['consultant', 'date', '-changed_at'], name='clinic_cons_consult_629bbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultantDailyPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('arrived_at', models.DateTimeField(verbose_name='ساعت ورود')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('in_session', 'در جلسه'), ('on_break', 'استراحت'), ('left', 'رفته')], default='present', max_length=20, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_presences', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='clinic.room', verbose_name='اتاق فعلی')),
            ],
            options={
                'verbose_name': 'حضور روزانه',
                'verbose_name_plural': 'حضورهای روزانه',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'status'], name='clinic_cons_date_1a93d4_idx'), models.Index(fields=['room', 'date'], name='clinic_cons_room_id_3dcb35_idx')],
                'unique_together': {('consultant', 'date')},
            },
        ),
    ]
