# Generated by Django 6.1.1 on 2026-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_room_alter_clinicsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.SlugField(blank=True, editable=False, help_text='به\u200cصورت خودکار ساخته می\u200cشود', unique=True, verbose_name='کد داخلی'),
        ),
    ]
