# Generated by Django 6.1.1 on 2026-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_room_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['order', 'id'], 'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق\u200cها'},
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='کد داخلی'),
        ),
        migrations.AlterField(
            model_name='room',
            name='color',
            field=models.CharField(default='#06b6d4', max_length=7, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب'),
        ),
    ]
