# Generated by Django 6.1.1 on 2026-09-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('face_photo', 'عکس صورت'), ('tongue_top', 'عکس روی زبان'), ('tongue_bottom', 'عکس زیر زبان'), ('ultrasound', 'سونوگرافی'), ('lab', 'آزمایش'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('ecg', 'نوار قلب / ECG'), ('pdf', 'فایل PDF'), ('other', 'سایر مدارک')], max_length=30, verbose_name='نوع مدرک')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='patient_docs/%Y/%m/', verbose_name='فایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='بیمار')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='records.visit', verbose_name='مراجعه مرتبط')),
            ],
            options={
                'verbose_name': 'مدرک بیمار',
                'verbose_name_plural': 'مدارک بیمار',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
