# Generated by Django 6.1.1 on 2026-09-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('patients', '0002_alter_patient_options_patient_assigned_consultant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'مدرک مراجع', 'verbose_name_plural': 'مدارک مراجع'},
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='مراجع'),
        ),
    ]
