# Generated by Django 6.1.1 on 2026-09-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.CharField(blank=True, max_length=200, verbose_name='نام کاربر (در لحظه)')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('view', 'مشاهده'), ('login', 'ورود'), ('logout', 'خروج'), ('login_failed', 'ورود ناموفق'), ('export', 'خروجی'), ('print', 'چاپ'), ('backup', 'پشتیبان\u200cگیری'), ('restore', 'بازیابی'), ('other', 'سایر')], max_length=20, verbose_name='نوع اقدام')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه رکورد')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='توضیح رکورد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش فعالیت',
                'verbose_name_plural': 'گزارش فعالیت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['user', '-created_at'], name='audit_user_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['model_name'], name='audit_model_idx')],
            },
        ),
    ]
