# Generated by Django 6.1.1 on 2026-09-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ نوبت')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('confirmed', 'تأیید شده'), ('arrived', 'حاضر شد'), ('in_progress', 'در حال ویزیت'), ('completed', 'انجام شد'), ('cancelled', 'لغو شده'), ('no_show', 'غیبت')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('in_person', 'حضوری'), ('phone', 'تلفنی'), ('online', 'آنلاین')], default='in_person', max_length=20, verbose_name='نحوه\u200cی ثبت')),
                ('reason', models.TextField(blank=True, verbose_name='علت مراجعه')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('payment_status', models.CharField(choices=[('not_required', 'نیاز به پرداخت ندارد'), ('unpaid', 'پرداخت\u200cنشده'), ('pending', 'در انتظار تأیید درگاه'), ('paid', 'پرداخت\u200cشده'), ('refunded', 'بازگشت داده شده'), ('failed', 'ناموفق')], default='not_required', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='مبلغ (تومان)')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('online', 'درگاه اینترنتی'), ('insurance', 'بیمه'), ('free', 'رایگان')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, default='', help_text='کد مرجع درگاه پرداخت (در صورت پرداخت آنلاین)', max_length=100, verbose_name='کد رهگیری پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='پیامک تأیید ارسال شد')),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال تأیید')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='پیامک یادآوری ارسال شد')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان یادآوری')),
                ('reminder_response', models.CharField(blank=True, default='', help_text='مثلاً: تأیید شد، لغو شد', max_length=200, verbose_name='پاسخ بیمار به یادآوری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='بیمار')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='طبیب')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='records.visit', verbose_name='مراجعه تبدیل\u200cشده')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'physician'], name='apt_date_phys_idx'), models.Index(fields=['date', 'start_time'], name='apt_date_time_idx'), models.Index(fields=['patient', '-date'], name='apt_patient_idx'), models.Index(fields=['status'], name='apt_status_idx'), models.Index(fields=['payment_status'], name='apt_payment_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('all_day', models.BooleanField(default=True, verbose_name='تمام روز')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='از ساعت')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='تا ساعت')),
                ('reason', models.CharField(choices=[('vacation', 'مرخصی'), ('holiday', 'تعطیل رسمی'), ('sick', 'بیماری'), ('conference', 'همایش / سفر'), ('personal', 'شخصی'), ('other', 'سایر')], default='vacation', max_length=20, verbose_name='دلیل')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL, verbose_name='طبیب')),
            ],
            options={
                'verbose_name': 'مرخصی / تعطیلی',
                'verbose_name_plural': 'مرخصی\u200cها و تعطیلی\u200cها',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['physician', 'date'], name='timeoff_phys_date_idx'), models.Index(fields=['-date'], name='timeoff_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('slot_duration', models.PositiveSmallIntegerField(default=15, help_text='مثال: ۱۵ دقیقه برای ویزیت معمولی، ۳۰ دقیقه برای مشاوره', verbose_name='طول هر نوبت (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL, verbose_name='طبیب')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
                'ordering': ['physician', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['physician', 'day_of_week', 'is_active'], name='sched_phys_day_idx')],
                'unique_together': {('physician', 'day_of_week', 'start_time')},
            },
        ),
    ]
