# Generated by Django 6.1.1 on 2026-09-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['physician', 'day_of_week', 'start_time'], 'verbose_name': 'برنامه هفتگی (قدیمی)', 'verbose_name_plural': 'برنامه\u200cهای هفتگی (قدیمی)'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='مراجع'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reminder_response',
            field=models.CharField(blank=True, default='', help_text='مثلاً: تأیید شد، لغو شد', max_length=200, verbose_name='پاسخ مراجع به یادآوری'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('confirmed', 'تأیید شده'), ('arrived', 'حاضر شد'), ('in_progress', 'در حال مشاوره'), ('completed', 'انجام شد'), ('cancelled', 'لغو شده'), ('no_show', 'غیبت')], default='scheduled', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='records.visit', verbose_name='جلسهٔ تبدیل\u200cشده'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_weekly_schedules', to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='slot_duration',
            field=models.PositiveSmallIntegerField(default=50, help_text='مثال: ۵۰ دقیقه برای مشاوره', verbose_name='طول هر نوبت (دقیقه)'),
        ),
    ]
