# Generated by Django 6.1.1 on 2026-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_weeklyschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='reason',
            field=models.CharField(choices=[('vacation', 'مرخصی'), ('holiday', 'تعطیل رسمی'), ('sick', 'مراجعی'), ('conference', 'همایش / سفر'), ('personal', 'شخصی'), ('other', 'سایر')], default='vacation', max_length=20, verbose_name='دلیل'),
        ),
    ]
