# Generated by Django 6.1.1 on 2026-09-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مراجعه')),
                ('prescription_serial', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='شماره سریال نسخه')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='علت مراجعه')),
                ('history', models.TextField(blank=True, verbose_name='شرح حال')),
                ('brief_history', models.TextField(blank=True, verbose_name='شرح مختصر بیماری')),
                ('diagnosis', models.TextField(blank=True, verbose_name='تشخیص')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='برنامه درمان')),
                ('follow_up', models.TextField(blank=True, verbose_name='نتیجه پیگیری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='بیمار')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='طبیب')),
            ],
            options={
                'verbose_name': 'مراجعه',
                'verbose_name_plural': 'مراجعات',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['patient', '-visited_at'], name='visit_patient_idx'), models.Index(fields=['physician', '-visited_at'], name='visit_physician_idx'), models.Index(fields=['-visited_at'], name='visit_date_idx')],
            },
        ),
    ]
