# Generated by Django 6.1.1 on 2026-09-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_assigned_consultant_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='brief_history',
            field=models.TextField(blank=True, verbose_name='شرح مختصر مراجعی'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='مراجع'),
        ),
    ]
