# Generated by Django 6.1.1 on 2026-09-24 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_timeoff_reason'),
        ('clinic', '0002_room_alter_clinicsettings_options_and_more'),
        ('patients', '0002_alter_patient_options_patient_assigned_consultant_and_more'),
        ('records', '0002_alter_visit_brief_history_alter_visit_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visited_at'], 'verbose_name': 'مراجعه (قدیمی)', 'verbose_name_plural': 'مراجعات (قدیمی)'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='brief_history',
            field=models.TextField(blank=True, verbose_name='شرح مختصر'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescription_serial',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='شماره سریال'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_snapshot', models.JSONField(default=dict, help_text='مشخصات سطح مشاور در لحظهٔ جلسه — تغییر تعرفه بعداً روی این جلسه اثر ندارد', verbose_name='اسنپ\u200cشات سطح')),
                ('scheduled_start', models.DateTimeField(verbose_name='شروع برنامه\u200cریزی\u200cشده')),
                ('scheduled_end', models.DateTimeField(verbose_name='پایان برنامه\u200cریزی\u200cشده')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان واقعی')),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت واقعی (دقیقه)')),
                ('pause_started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع وقفه')),
                ('total_paused_seconds', models.PositiveIntegerField(default=0, verbose_name='مجموع وقفه\u200cها (ثانیه)')),
                ('session_type', models.CharField(choices=[('individual', 'فردی'), ('couple', 'زوج'), ('family', 'خانواده'), ('group', 'گروه'), ('phone', 'تلفنی'), ('online', 'آنلاین')], default='individual', max_length=20, verbose_name='نوع جلسه')),
                ('session_number', models.PositiveIntegerField(blank=True, help_text='جلسهٔ چندم از این مراجع', null=True, verbose_name='شمارهٔ جلسه')),
                ('extension_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل تمدید')),
                ('secretary_note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت منشی')),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ محاسبه\u200cشده')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='تخفیف (٪)')),
                ('final_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ نهایی')),
                ('payment_status', models.CharField(choices=[('pending', 'منتظر پرداخت'), ('paid', 'پرداخت\u200cشده'), ('deferred', 'نسیه'), ('partial', 'پرداخت جزئی'), ('insurance', 'بیمه'), ('waived', 'بخشیده\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('online', 'درگاه اینترنتی'), ('insurance', 'بیمه'), ('wallet', 'کیف پول'), ('other', 'سایر')], max_length=20, verbose_name='روش پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پرداخت\u200cشده')),
                ('remaining_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مانده')),
                ('payment_note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت پرداخت')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی\u200cشده'), ('in_progress', 'در حال مشاوره'), ('paused', 'وقفه'), ('awaiting_payment', 'منتظر پرداخت'), ('completed', 'تسویه\u200cشده'), ('cancelled', 'لغو\u200cشده'), ('no_show', 'عدم مراجعه')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='appointments.appointment', verbose_name='نوبت')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='patients.patient', verbose_name='مراجع')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='clinic.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='متن تحلیل')),
                ('has_audio', models.BooleanField(default=False, verbose_name='دارای صوت')),
                ('audio_file', models.FileField(blank=True, upload_to='session_audio/%Y/%m/', verbose_name='فایل صوتی')),
                ('audio_duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت صوت (ثانیه)')),
                ('audio_size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حجم صوت (بایت)')),
                ('audio_format', models.CharField(blank=True, max_length=10, verbose_name='فرمت صوت')),
                ('transcript', models.TextField(blank=True, verbose_name='متن تبدیل\u200cشده')),
                ('transcript_source', models.CharField(blank=True, choices=[('whisper', 'Whisper AI'), ('manual', 'دستی'), ('voice_typing', 'تایپ صوتی مرورگر'), ('vosk', 'Vosk')], max_length=20, verbose_name='منبع تبدیل')),
                ('transcript_edited', models.BooleanField(default=False, verbose_name='متن ویرایش شد')),
                ('transcript_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ویرایش متن')),
                ('soap_subjective', models.TextField(blank=True, verbose_name='S — ذهنی')),
                ('soap_objective', models.TextField(blank=True, verbose_name='O — عینی')),
                ('soap_assessment', models.TextField(blank=True, verbose_name='A — ارزیابی')),
                ('soap_plan', models.TextField(blank=True, verbose_name='P — برنامه')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('severity', models.CharField(blank=True, choices=[('mild', 'خفیف'), ('moderate', 'متوسط'), ('severe', 'شدید')], max_length=20, verbose_name='شدت')),
                ('progress', models.CharField(blank=True, choices=[('better', 'بهتر'), ('no_change', 'بدون تغییر'), ('worse', 'بدتر')], max_length=20, verbose_name='پیشرفت')),
                ('ai_summary', models.TextField(blank=True, verbose_name='خلاصهٔ AI')),
                ('ai_key_topics', models.JSONField(blank=True, default=list, verbose_name='موضوعات کلیدی AI')),
                ('ai_sentiment', models.CharField(blank=True, max_length=20, verbose_name='احساس AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('finalized', 'نهایی'), ('signed', 'امضاشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان نهایی\u200cسازی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='records.session', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'یادداشت جلسه',
                'verbose_name_plural': 'یادداشت\u200cهای جلسه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionNoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='نسخه')),
                ('content', models.TextField(blank=True, verbose_name='متن')),
                ('transcript', models.TextField(blank=True, verbose_name='متن تبدیل\u200cشده')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('change_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل تغییر')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='records.sessionnote', verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'نسخهٔ یادداشت',
                'verbose_name_plural': 'نسخه\u200cهای یادداشت',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['client', '-scheduled_start'], name='sess_client_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['consultant', '-scheduled_start'], name='sess_consultant_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', '-scheduled_start'], name='sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['room', 'scheduled_start'], name='sess_room_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-scheduled_start'], name='sess_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionnote',
            index=models.Index(fields=['-created_at'], name='note_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionnote',
            index=models.Index(fields=['status'], name='note_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionnoterevision',
            unique_together={('note', 'version')},
        ),
    ]
