# Generated by Django 6.1.1 on 2026-09-24 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='نام فایل')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], default='success', max_length=10, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'پشتیبان',
                'verbose_name_plural': 'پشتیبان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
