# Generated by Django 6.1.1 on 2026-09-24 08:24

import django.core.validators
import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='شماره پرونده')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('national_code', models.CharField(error_messages={'required': 'وارد کردن کد ملی الزامی است.', 'unique': 'این کد ملی قبلاً برای بیمار دیگری ثبت شده است.'}, max_length=10, null=True, unique=True, validators=[patients.validators.validate_iranian_national_code], verbose_name='کد ملی')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='اتباع خارجی')),
                ('foreign_id', models.CharField(blank=True, max_length=30, verbose_name='شماره شناسایی اتباع')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'بیوه')], max_length=10, verbose_name='وضعیت تأهل')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='شغل')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='تحصیلات')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('mobile', models.CharField(error_messages={'required': 'وارد کردن شماره موبایل الزامی است.'}, max_length=15, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد. مثال: ۰۹۱۲۳۴۵۶۷۸۹', regex='^09(1[0-9]|2[0-9]|3[0-9]|9[0-9])\\d{7}$')], verbose_name='تلفن همراه')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن اضطراری')),
                ('emergency_name', models.CharField(blank=True, max_length=100, verbose_name='نام فرد اضطراری')),
                ('country', models.CharField(default='ایران', max_length=50, verbose_name='کشور')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='خیابان')),
                ('alley', models.CharField(blank=True, max_length=100, verbose_name='کوچه')),
                ('plaque', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('address_note', models.TextField(blank=True, verbose_name='توضیحات آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='patient_name_idx'), models.Index(fields=['mobile'], name='patient_mobile_idx'), models.Index(fields=['-created_at'], name='patient_created_idx'), models.Index(fields=['last_name'], name='patient_lastname_idx')],
            },
        ),
    ]
