# Generated by Django 6.1.1 on 2026-09-24 11:26

import django.db.models.deletion
import patients.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'مراجع', 'verbose_name_plural': 'مراجعین'},
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='مشاور اصلی'),
        ),
        migrations.AddField(
            model_name='patient',
            name='confidentiality_level',
            field=models.CharField(choices=[('normal', 'عادی'), ('confidential', 'محرمانه'), ('special', 'ویژه')], default='normal', max_length=20, verbose_name='سطح محرمانگی'),
        ),
        migrations.AddField(
            model_name='patient',
            name='credit_limit',
            field=models.DecimalField(decimal_places=0, default=0, help_text='۰ = بدون سقف', max_digits=12, verbose_name='سقف اعتبار (تومان)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='برای مراجعین زیر ۱۸ سال الزامی است', max_length=100, verbose_name='نام سرپرست / ولی'),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='تلفن سرپرست'),
        ),
        migrations.AddField(
            model_name='patient',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مجموع بدهی انباشته', max_digits=12, verbose_name='مانده بدهی (تومان)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('self', 'خودمعرف'), ('friend', 'معرفی دوست / آشنا'), ('doctor', 'پزشک'), ('internet', 'اینترنت'), ('instagram', 'شبکه\u200cهای اجتماعی'), ('school', 'مدرسه / دانشگاه'), ('court', 'دادگاه / ارجاع قضایی'), ('insurance', 'بیمه'), ('other', 'سایر')], max_length=20, verbose_name='منبع آشنایی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(error_messages={'required': 'وارد کردن کد ملی الزامی است.', 'unique': 'این کد ملی قبلاً برای مراجع دیگری ثبت شده است.'}, max_length=10, null=True, unique=True, validators=[patients.validators.validate_iranian_national_code], verbose_name='کد ملی'),
        ),
        migrations.CreateModel(
            name='ClientNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(verbose_name='شکایت اصلی')),
                ('history_of_present_illness', models.TextField(verbose_name='تاریخچهٔ مشکل فعلی')),
                ('past_psychiatric_history', models.TextField(blank=True, verbose_name='سابقهٔ روان\u200cپزشکی')),
                ('family_history', models.TextField(blank=True, verbose_name='سابقهٔ خانوادگی')),
                ('medical_history', models.TextField(blank=True, verbose_name='سابقهٔ پزشکی')),
                ('medications', models.TextField(blank=True, verbose_name='داروهای مصرفی')),
                ('substance_use', models.TextField(blank=True, verbose_name='مصرف مواد')),
                ('social_history', models.TextField(blank=True, verbose_name='وضعیت اجتماعی')),
                ('education_occupation', models.TextField(blank=True, verbose_name='تحصیلات و شغل')),
                ('marital_family_status', models.TextField(blank=True, verbose_name='وضعیت تأهل و خانواده')),
                ('suicide_risk', models.CharField(choices=[('none', 'بدون خطر'), ('low', 'کم'), ('moderate', 'متوسط'), ('high', 'بالا')], default='none', max_length=20, verbose_name='خطر خودکشی')),
                ('self_harm_risk', models.CharField(choices=[('none', 'بدون خطر'), ('low', 'کم'), ('moderate', 'متوسط'), ('high', 'بالا')], default='none', max_length=20, verbose_name='خطر خودآسیبی')),
                ('risk_notes', models.TextField(blank=True, verbose_name='یادداشت خطر')),
                ('provisional_diagnosis', models.TextField(blank=True, verbose_name='تشخیص اولیه')),
                ('dsm_codes', models.JSONField(blank=True, default=list, verbose_name='کدهای DSM-5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narrative', to='patients.patient', verbose_name='مراجع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narratives_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narratives_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'شرح حال',
                'verbose_name_plural': 'شرح حال\u200cها',
            },
        ),
    ]
