# Generated by Django 6.1.1 on 2026-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_assigned_consultant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='منطقه / محله'),
        ),
    ]
