# Generated by Django 6.1.1 on 2026-09-26 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('schedule_changed', 'تغییر برنامه'), ('leave_request', 'مرخصی / استثنا'), ('new_session', 'جلسهٔ جدید'), ('session_overdue', 'جلسهٔ طولانی'), ('payment_deferred', 'نسیه'), ('survey_response', 'نظر مراجع'), ('system_alert', 'هشدار سیستم')], max_length=30, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(blank=True, verbose_name='متن')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
